// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function LoadModel(modelID: string): $CancellablePromise<$models.DashboardSnapshot> {
    return $Call.ByID(4024759518, modelID);
}

export function Snapshot(): $CancellablePromise<$models.DashboardSnapshot> {
    return $Call.ByID(217719277);
}

export function StopModel(): $CancellablePromise<$models.DashboardSnapshot> {
    return $Call.ByID(3067977082);
}
