// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AdvertisedModel {
    "id": string;
    "context": number;
    "trainingContext"?: number;
    "quantization"?: string;
}

export interface DashboardSnapshot {
    "gatewayEndpoint": string;
    "gatewayHealth": string;
    "model": ModelSnapshot;
    "models": AdvertisedModel[] | null;
    "updatedAt": string;
    "error"?: string;
}

export interface ModelSnapshot {
    "kind": string;
    "preset": string;
    "health"?: boolean | null;
    "residentBytes"?: number;
    "startedAt"?: string;
}
