// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AdvertisedModel {
    "id": string;
    "context": number;
    "trainingContext"?: number;
    "quantization"?: string;
    "sizeBytes"?: number;
    "cached": boolean;
    "canDelete": boolean;
    "protected"?: boolean;
    "custom"?: boolean;
    "path"?: string;
}

export interface DashboardSnapshot {
    "gatewayEndpoint": string;
    "gatewayHealth": string;
    "model": ModelSnapshot;
    "loading"?: LoadingSnapshot | null;
    "models": AdvertisedModel[] | null;
    "logFile"?: string;
    "logLines"?: string[] | null;
    "updatedAt": string;
    "error"?: string;
}

export interface LoadingSnapshot {
    "model": string;
    "phase": string;
    "startedAt": string;
    "downloaded"?: number;
    "total"?: number;
    "bytesPerSecond"?: number;
    "etaSeconds"?: number;
    "error"?: string;
}

export interface ModelSnapshot {
    "kind": string;
    "preset": string;
    "health"?: boolean | null;
    "residentBytes"?: number;
    "startedAt"?: string;
}
